services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    ExchangeRates\:
        resource: '../../'

    ExchangeRates\NbpRatesRepository: ~
    ExchangeRates\RatesRepository: '@ExchangeRates\NbpRatesRepository'

    ExchangeRates\CurrencyCommissionProviderEurUsd:
        tags:
            - { name: currency_commision_provider }

    ExchangeRates\CurrencyCommissionProviderOther:
        tags:
            - { name: currency_commision_provider }

    ExchangeRates\CurrencySpreadService:
        arguments:
            $providers: !tagged currency_commision_provider